version: '3.7'
services:
    database:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=p4ssw0rd
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./db/postgres-da  ta:/var/lib/postgresql/data
          - ./db/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    web:
      tty: true
      stdin_open: true
      build: .
      ports:
        - "5000:5000"
      depends_on:
        - database
      volumes:
        - .:/code
      environment:
        - FLASK_APP=model/api.py
