version: '3.7'
services:
    postgres:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=p4ssw0rd
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    gunicorn:
      depends_on:
        - postgres
      image: continuumio/miniconda3:4.7.12
      ports:
        - "5000:5000"
      restart: always
      environment:
        PGDB: postgres
        PGUSER: postgres
        PGHOST: postgres:5438
        PGPASSWORD: p4ssw0rd
