-- create table for eployee attrition
CREATE TABLE IF NOT EXISTS employee_attrition (
  age INT NOT NULL,
  attrition varchar(255),
  business_travel varchar(255),
  daily_rate INT NOT NULL,
  department varchar(255),
  distance_from_home INT NOT NULL,
  education INT NOT NULL,
  education_field varchar(255),
  employee_count INT NOT NULL,
  employee_number serial NOT NULL,
  environment_satisfaction INT NOT NULL,
  gender varchar(255),
  hourly_rate INT NOT NULL,
  job_involvement INT NOT NULL,
  job_level INT NOT NULL,
  job_role varchar(255),
  job_satisfaction INT NOT NULL,
  marital_status varchar(255),
  monthly_income double precision NOT NULL,
  monthly_rate double precision NOT NULL,
  num_companies_worked INT NOT NULL,
  over18 varchar(255),
  over_time varchar(255),
  percent_salary_hike INT NOT NULL,
  performance_rating INT NOT NULL,
  relationship_satisfaction INT NOT NULL,
  standard_hours INT NOT NULL,
  stock_option_level INT NOT NuLL,
  total_working_years INT NOT NULL,
  training_times_last_year INT NOT NULL,
  work_life_balance INT NOT NULL,
  years_at_company INT NOT NULL,
  years_in_current_role INT NOT NULL,
  years_since_last_promotion INT NOT NULL,
  years_with_curr_manager INT NOT NULL,
  turnover_score double precision NOT NULL,
  PRIMARY KEY(employee_number)
);
